# -*- coding: utf-8 -*-
"""GENAI-capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCVCd8zrLf48e189tVq6rckKxzUhlbGQ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

# Data → Cleaning → Selection → Splitting → Scaling → Training → Evaluation → Prediction → Deployment → Reporting


# --- PRE-PROCESSING & TRAINING (Wrapped for Backend) ---
if __name__ == "__main__":
    # loading the Dataset
    data = pd.read_csv('crop_yield.csv')
    df = pd.DataFrame(data)

    # df.info()
    df = df.dropna()
    # check for the missing values
    df.isna().sum()

    df.head()

    # figuring out the features and labels
    X = df.drop('Yield_tons_per_hectare',axis=1)    # features
    y = df['Yield_tons_per_hectare']                # label (target)

    # one hot encoding of categorical data and outlier handeling of numerical data using IQR method
    categorical_cols = ['Region', 'Soil_Type', 'Crop', 'Weather_Condition']

    numerical_cols = ['Rainfall_mm', 'Temperature_Celsius', 'Days_to_Harvest']

    Q1 = df[numerical_cols].quantile(0.25)
    Q3 = df[numerical_cols].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Clip values to lower and upper bounds
    df[numerical_cols] = df[numerical_cols].clip(lower=lower, upper=upper, axis=1)

    # drop first gives more efficiency
    X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)
    X

    X.info() # summary of the input

    # standard scaling for making all features come to the same scale
    scaler = StandardScaler()
    X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

    X

    # train test split of 90/10

    from sklearn.model_selection import train_test_split

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.1, random_state=42
    )
    # print(X_train.isnull().sum())
    print("Train size:", X_train.shape)
    print("Test size:", X_test.shape)

    # created and trained the model of Linear Regression

    lr = LinearRegression()
    lr.fit(X_train, y_train)
    y_pred_lr = lr.predict(X_test)

    # evaluation metrics for Linear Regression

    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

    print("\n--- Linear Regression ---")
    print(f"R²:   {r2_score(y_test, y_pred_lr):.4f}")
    print(f"MAE:  {mean_absolute_error(y_test, y_pred_lr):.4f}")
    print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_lr)):.4f}")

    # created and trained the model of Decision Tree

    dt_final = DecisionTreeRegressor(
        max_depth=15,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42
    )
    dt_final.fit(X_train, y_train)

    # evaluation metrics for Decision Tree (ensuring there was no overfitting)

    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
    import numpy as np

    # Predictions
    y_pred_train = dt_final.predict(X_train)
    y_pred_test = dt_final.predict(X_test)

    # Metrics
    print("=== Decision Tree Final Model ===")
    print(f"{'R²':<10} {r2_score(y_train, y_pred_train):>10.4f} {r2_score(y_test, y_pred_test):>10.4f}")
    print(f"{'MAE':<10} {mean_absolute_error(y_train, y_pred_train):>10.4f} {mean_absolute_error(y_test, y_pred_test):>10.4f}")
    print(f"{'RMSE':<10} {np.sqrt(mean_squared_error(y_train, y_pred_train)):>10.4f} {np.sqrt(mean_squared_error(y_test, y_pred_test)):>10.4f}")

    # Overfitting check
    diff = r2_score(y_train, y_pred_train) - r2_score(y_test, y_pred_test)
    print(f"\nR² Difference: {diff:.4f}")

    if diff < 0.05:
        print("No overfitting — perfect!")
    elif diff < 0.10:
        print("Slight overfitting — acceptable")
    else:
        print("Overfitting — tune further")

    # we choose Linear Regression over Decision Tree because R2 score for Linear regression is better than decsiion tree and MAE and RMSE is also lower

    # then we plotted our data and got the best fit line for it

    import plotly.graph_objects as go
    import numpy as np

    # Best fit line using numpy
    m, b = np.polyfit(y_test, y_pred_lr, 1)
    x_line = np.linspace(y_test.min(), y_test.max(), 100)
    y_line = m * x_line + b

    fig = go.Figure()

    # Scatter points
    fig.add_trace(go.Scatter(
        x=y_test,
        y=y_pred_lr,
        mode='markers',
        marker=dict(color='steelblue', size=4, opacity=0.4),
        name='Predicted vs Actual'
    ))

    # Best fit line
    fig.add_trace(go.Scatter(
        x=x_line,
        y=y_line,
        mode='lines',
        line=dict(color='red', width=2),
        name='Best Fit Line'
    ))

    fig.update_layout(
        title=f'Linear Regression — Best Fit Line<br>R²: {r2_score(y_test, y_pred_lr):.4f}',
        xaxis_title='Actual Yield',
        yaxis_title='Predicted Yield',
        height=500
    )

    # fig.show() # Commented for backend deployment

    import plotly.express as px
    import pandas as pd


    train_df = X_train.copy()
    train_df['Yield_tons_per_hectare'] = y_train.values

    corr_matrix = train_df.corr(numeric_only=True)

    fig = px.imshow(
        corr_matrix,
        text_auto=True,
        color_continuous_scale='RdYlGn',
        title='Correlation Heatmap — Crop Yield Dataset',
        aspect='auto'
    )

    fig.update_layout(height=600, width=700)
    # fig.show() # Commented for backend deployment




# from google.colab import userdata
# GROQ_API_KEY=userdata.get('GROQ_API_KEY')

# import os
# os.environ["GROQ_API_KEY"] = GROQ_API_KEY

"""
=============================================================================
  MILESTONE 2 — AGENTIC FARM ADVISORY SYSTEM
  Crop Yield Prediction + LangGraph + RAG + Groq (Llama 3.1)
=============================================================================
"""

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────────────────────────────
import os
import json
import logging
import pandas as pd
import numpy as np
from groq import Groq
from typing import TypedDict, List
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import chromadb
from chromadb.utils import embedding_functions
from langgraph.graph import StateGraph, END, START

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────
MODEL_NAME   = "llama-3.1-8b-instant"
DATASET_PATH = "crop_yield.csv"
NUM_COLS     = ["Rainfall_mm", "Temperature_Celsius", "Days_to_Harvest"]
CAT_COLS     = ["Region", "Soil_Type", "Crop", "Weather_Condition"]

YIELD_LOW_THRESHOLD  = 3.0   # tons/hectare
YIELD_HIGH_THRESHOLD = 6.0

AGRONOMY_DOCS = [
    # Crop-specific
    "Rice requires consistent irrigation and flooded fields for high yield. It grows best in clay soil that retains water.",
    "Wheat grows best in loam soil with moderate rainfall between 400–600mm. Avoid waterlogging at root level.",
    "Cotton is highly sensitive to waterlogging. Sandy soil with drip irrigation is ideal for cotton cultivation.",
    "Maize yields improve significantly with nitrogen-rich fertilizers and regular irrigation in warm climates.",
    "Barley is drought-tolerant but sensitive to extreme heat during flowering. Reduce irrigation during grain fill.",
    "Soybeans fix atmospheric nitrogen naturally. Phosphorus supplementation is recommended in silty soils.",
    # Soil-specific
    "Sandy soil drains quickly and loses nutrients fast. Frequent low-volume irrigation and organic matter addition recommended.",
    "Clay soil retains moisture well but risks root rot if over-irrigated. Allow surface drying between watering cycles.",
    "Loam soil is the most balanced soil type. It supports almost all crops with standard irrigation practices.",
    "Peaty soil is highly acidic and nutrient-rich. Lime application is often required to raise pH before planting.",
    "Silty soil has high moisture retention and is prone to compaction. Avoid heavy machinery on wet silty fields.",
    # Weather-specific
    "Sunny weather increases evapotranspiration rates. Increase irrigation frequency to compensate for water loss.",
    "Rainy conditions increase risk of fungal diseases and leaf blight. Monitor crops closely; apply preventive fungicides.",
    "Cloudy weather reduces photosynthesis output. Avoid heavy fertilization during prolonged cloudy periods.",
    "Humid weather accelerates pest breeding cycles. Bollworms and aphids are common in cotton during humid seasons.",
    # Yield risk and mitigation
    "Low yield (below 3 tons/hectare) is often linked to nutrient deficiency, pest infestation, or poor water management.",
    "Medium yield (3–6 tons/hectare) can be improved through precision fertilization and optimized irrigation scheduling.",
    "High yield (above 6 tons/hectare) indicates good agronomic practices. Maintain current protocols and monitor soil health.",
    "Crop rotation with legumes restores soil nitrogen naturally and reduces dependence on synthetic fertilizers.",
    "Drip irrigation reduces water usage by up to 40% compared to flood irrigation and is ideal for sandy regions.",
]

# ─────────────────────────────────────────────────────────────────────────────
# STATE DEFINITION
# ─────────────────────────────────────────────────────────────────────────────
class FarmState(TypedDict):
    farm_data:        dict
    yield_prediction: float
    yield_category:   str
    retrieved_docs:   List[str]
    llm_reasoning:    str
    advisory_report:  dict
    error:            str

# ─────────────────────────────────────────────────────────────────────────────
# GLOBALS (initialised once via setup functions)
# ─────────────────────────────────────────────────────────────────────────────
_collection:   chromadb.Collection = None
_model:        LinearRegression     = None
_scaler:       StandardScaler       = None
_feature_cols: List[str]            = None
_groq_client:  Groq                 = None

# ─────────────────────────────────────────────────────────────────────────────
# GROQ CLIENT — lazy singleton
# ─────────────────────────────────────────────────────────────────────────────
def get_groq() -> Groq:
    global _groq_client
    if _groq_client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise EnvironmentError("GROQ_API_KEY is not set. Add it to Colab Secrets.")
        _groq_client = Groq(api_key=api_key)
    return _groq_client

# ─────────────────────────────────────────────────────────────────────────────
# SETUP: KNOWLEDGE BASE
# ─────────────────────────────────────────────────────────────────────────────
def setup_knowledge_base() -> None:
    """Initialise ChromaDB with agronomy knowledge. Idempotent — safe to call multiple times."""
    global _collection

    log.info("Setting up knowledge base...")
    client = chromadb.EphemeralClient()
    emb_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )
    _collection = client.get_or_create_collection(
        name="agronomy_kb",
        embedding_function=emb_fn
    )

    if _collection.count() == 0:
        _collection.add(
            documents=AGRONOMY_DOCS,
            ids=[f"doc_{i}" for i in range(len(AGRONOMY_DOCS))]
        )
        log.info(f"Knowledge base populated with {len(AGRONOMY_DOCS)} chunks.")
    else:
        log.info(f"Knowledge base already contains {_collection.count()} chunks.")

# ─────────────────────────────────────────────────────────────────────────────
# SETUP: ML MODEL
# ─────────────────────────────────────────────────────────────────────────────
import joblib

def setup_model() -> None:
    """Load pre-trained model or train on crop_yield.csv if missing."""
    global _model, _scaler, _feature_cols

    MODEL_FILE = "model.joblib"
    
    if os.path.exists(MODEL_FILE):
        log.info(f"Loading persistent model from '{MODEL_FILE}'...")
        data = joblib.load(MODEL_FILE)
        _model = data['model']
        _scaler = data['scaler']
        _feature_cols = data['feature_cols']
        log.info("Model loaded successfully.")
        return

    log.info(f"Persistent model not found. Training on '{DATASET_PATH}' (this may take time)...")
    df = pd.read_csv(DATASET_PATH)

    # Drop nulls (mirrors M1)
    df = df.dropna()

    # Boolean → int
    df["Fertilizer_Used"] = df["Fertilizer_Used"].astype(int)
    df["Irrigation_Used"]  = df["Irrigation_Used"].astype(int)

    # IQR outlier clipping (mirrors M1)
    Q1    = df[NUM_COLS].quantile(0.25)
    Q3    = df[NUM_COLS].quantile(0.75)
    IQR   = Q3 - Q1
    df[NUM_COLS] = df[NUM_COLS].clip(Q1 - 1.5 * IQR, Q3 + 1.5 * IQR, axis=1)

    # One-hot encode categoricals (mirrors M1 — drop_first=True)
    X = pd.get_dummies(
        df.drop("Yield_tons_per_hectare", axis=1),
        columns=CAT_COLS,
        drop_first=True
    )
    y = df["Yield_tons_per_hectare"]

    _feature_cols = X.columns.tolist()

    # Standard scaling on numerical columns only (mirrors M1)
    _scaler  = StandardScaler()
    X[NUM_COLS] = _scaler.fit_transform(X[NUM_COLS])

    # Train
    _model = LinearRegression()
    _model.fit(X, y)
    
    # Save for next time
    joblib.dump({'model': _model, 'scaler': _scaler, 'feature_cols': _feature_cols}, MODEL_FILE)
    log.info(f"Model trained on {len(df):,} rows and saved to '{MODEL_FILE}'")


# ─────────────────────────────────────────────────────────────────────────────
# HELPER: LLM CALL
# ─────────────────────────────────────────────────────────────────────────────
def _call_llm(prompt: str, json_mode: bool = False) -> str:
    """Single wrapper for all Groq calls. Raises on failure."""
    kwargs = dict(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
    )
    if json_mode:
        kwargs["response_format"] = {"type": "json_object"}

    response = get_groq().chat.completions.create(**kwargs)
    return response.choices[0].message.content

# ─────────────────────────────────────────────────────────────────────────────
# HELPER: NORMALIZE REPORT
# ─────────────────────────────────────────────────────────────────────────────
def _normalize_report(raw: dict, state: FarmState) -> dict:
    """Guarantee the advisory report has exactly the expected schema."""
    farm = state["farm_data"]

    def _to_action_list(actions) -> List[dict]:
        if not isinstance(actions, list):
            return []
        result = []
        for a in actions:
            if isinstance(a, dict):
                result.append({
                    "task":        a.get("task", "Recommendation"),
                    "description": a.get("description", str(a))
                })
            else:
                result.append({"task": "Recommendation", "description": str(a)})
        return result

    return {
        "crop_summary": {
            "crop_name":        farm.get("Crop", "N/A"),
            "region":           farm.get("Region", "N/A"),
            "yield_prediction": f"{state['yield_prediction']:.2f} tons/hectare",
            "yield_category":   state["yield_category"],
        },
        "field_status": {
            "soil_type":   farm.get("Soil_Type", "N/A"),
            "rainfall_mm": farm.get("Rainfall_mm", "N/A"),
            "temperature": f"{farm.get('Temperature_Celsius', 'N/A')} °C",
            "irrigation":  farm.get("Irrigation_Used", "N/A"),
            "fertilizer":  farm.get("Fertilizer_Used", "N/A"),
            "weather":     farm.get("Weather_Condition", "N/A"),
        },
        "yield_risk_level":     state["yield_category"],
        "recommended_actions":  _to_action_list(raw.get("recommended_actions", [])),
        "agronomic_references": [str(r) for r in raw.get("agronomic_references", [])],
        "safety_disclaimer":    raw.get(
            "safety_disclaimer",
            "Always consult a certified local agronomist before implementing recommendations."
        ),
    }

# ─────────────────────────────────────────────────────────────────────────────
# NODE 1 — PREDICT
# ─────────────────────────────────────────────────────────────────────────────
def node_predict(state: FarmState) -> dict:
    """Preprocess farm input and run yield prediction."""
    log.info("[Node 1] Running yield prediction...")
    try:
        data = state["farm_data"].copy()
        data["Fertilizer_Used"] = int(data["Fertilizer_Used"])
        data["Irrigation_Used"]  = int(data["Irrigation_Used"])

        row = pd.DataFrame([data])
        row = pd.get_dummies(row, columns=CAT_COLS, drop_first=True)
        row = row.reindex(columns=_feature_cols, fill_value=0)
        row[NUM_COLS] = _scaler.transform(row[NUM_COLS])

        prediction = float(_model.predict(row)[0])
        category   = (
            "Low"    if prediction < YIELD_LOW_THRESHOLD  else
            "High"   if prediction > YIELD_HIGH_THRESHOLD else
            "Medium"
        )

        log.info(f"[Node 1] Prediction: {prediction:.2f} t/ha | Category: {category}")
        return {"yield_prediction": prediction, "yield_category": category, "error": ""}

    except Exception as exc:
        log.error(f"[Node 1] Prediction failed: {exc}")
        return {"error": str(exc), "yield_prediction": 0.0, "yield_category": "Unknown"}

# ─────────────────────────────────────────────────────────────────────────────
# NODE 2 — RETRIEVE
# ─────────────────────────────────────────────────────────────────────────────
def node_retrieve(state: FarmState) -> dict:
    """Query ChromaDB for the most relevant agronomy context."""
    if state.get("error"):
        return {"retrieved_docs": []}

    log.info("[Node 2] Retrieving agronomy context...")
    farm  = state["farm_data"]
    query = (
        f"{farm['Crop']} {farm['Soil_Type']} {farm['Weather_Condition']} "
        f"{state['yield_category']} yield"
    )
    results = _collection.query(query_texts=[query], n_results=4)
    docs    = results["documents"][0]

    log.info(f"[Node 2] Retrieved {len(docs)} relevant chunks.")
    return {"retrieved_docs": docs}

# ─────────────────────────────────────────────────────────────────────────────
# NODE 3 — REASON
# ─────────────────────────────────────────────────────────────────────────────
def node_reason(state: FarmState) -> dict:
    """LLM agronomic reasoning over prediction + retrieved context."""
    if state.get("error"):
        return {"llm_reasoning": ""}

    log.info("[Node 3] Running LLM reasoning...")
    try:
        prompt = f"""You are a senior agronomist advising a farmer.

FARM DATA:
{json.dumps(state['farm_data'], indent=2)}

YIELD PREDICTION: {state['yield_prediction']:.2f} tons/hectare
YIELD CATEGORY: {state['yield_category']}

AGRONOMIC CONTEXT (from knowledge base):
{chr(10).join(f"- {d}" for d in state['retrieved_docs'])}

Based only on the information above:
1. Explain WHY this yield was predicted given the farm conditions.
2. Identify the TOP 3 risk factors affecting yield.
3. Suggest 3–5 SPECIFIC, actionable farming recommendations.

Be precise and practical. Do not hallucinate facts beyond what is provided."""

        reasoning = _call_llm(prompt)
        log.info("[Node 3] Reasoning complete.")
        return {"llm_reasoning": reasoning}

    except Exception as exc:
        log.error(f"[Node 3] LLM call failed: {exc}")
        return {"error": str(exc), "llm_reasoning": ""}

# ─────────────────────────────────────────────────────────────────────────────
# NODE 4 — GENERATE REPORT
# ─────────────────────────────────────────────────────────────────────────────
def node_report(state: FarmState) -> dict:
    """Convert LLM reasoning into a structured advisory report."""
    if state.get("error") and not state.get("llm_reasoning"):
        return {"advisory_report": _normalize_report({}, state)}

    log.info("[Node 4] Generating structured report...")
    try:
        prompt = f"""Convert the agronomic reasoning below into a structured JSON report.

REASONING:
{state['llm_reasoning']}

Return ONLY valid JSON with exactly these keys:
- recommended_actions: list of objects, each with "task" (short title) and "description" (full action)
- agronomic_references: list of strings citing the agronomic principles used
- safety_disclaimer: a one-sentence disclaimer about consulting professionals

No markdown, no explanation — pure JSON only."""

        raw_json = _call_llm(prompt, json_mode=True)
        report   = _normalize_report(json.loads(raw_json), state)

        log.info("[Node 4] Report generated successfully.")
        return {"advisory_report": report}

    except Exception as exc:
        log.error(f"[Node 4] Report generation failed: {exc}")
        return {"advisory_report": _normalize_report({}, state)}

# ─────────────────────────────────────────────────────────────────────────────
# NODE 5 — DISPLAY REPORT
# ─────────────────────────────────────────────────────────────────────────────
def node_display(state: FarmState) -> dict:
    """Pretty-print the final advisory report to console."""
    r = state.get("advisory_report", {})

    cs = r.get("crop_summary",  {})
    fs = r.get("field_status",  {})

    print("\n" + "═" * 60)
    print("  🌾  FARM ADVISORY REPORT")
    print("═" * 60)

    print(f"\n📋  CROP SUMMARY")
    print(f"    Crop      : {cs.get('crop_name', 'N/A')}")
    print(f"    Region    : {cs.get('region', 'N/A')}")
    print(f"    Yield     : {cs.get('yield_prediction', 'N/A')}")
    print(f"    Category  : {cs.get('yield_category', 'N/A')}")

    print(f"\n🌱  FIELD STATUS")
    print(f"    Soil      : {fs.get('soil_type', 'N/A')}")
    print(f"    Rainfall  : {fs.get('rainfall_mm', 'N/A')} mm")
    print(f"    Temp      : {fs.get('temperature', 'N/A')}")
    print(f"    Weather   : {fs.get('weather', 'N/A')}")
    print(f"    Fertilizer: {'Yes' if fs.get('fertilizer') else 'No'}")
    print(f"    Irrigation: {'Yes' if fs.get('irrigation') else 'No'}")

    print(f"\n⚠️   YIELD RISK LEVEL: {r.get('yield_risk_level', 'N/A')}")

    print(f"\n✅  RECOMMENDED ACTIONS")
    actions = r.get("recommended_actions", [])
    if actions:
        for i, a in enumerate(actions, 1):
            print(f"    {i}. [{a.get('task', '')}] {a.get('description', '')}")
    else:
        print("    No actions available.")

    print(f"\n📚  AGRONOMIC REFERENCES")
    refs = r.get("agronomic_references", [])
    if refs:
        for ref in refs:
            print(f"    • {ref}")
    else:
        print("    No references available.")

    print(f"\n⚠️   DISCLAIMER")
    print(f"    {r.get('safety_disclaimer', 'Consult a certified agronomist.')}")

    print("\n" + "═" * 60)
    return state

# ─────────────────────────────────────────────────────────────────────────────
# LANGGRAPH — BUILD & COMPILE
# ─────────────────────────────────────────────────────────────────────────────
def build_graph() -> StateGraph:
    g = StateGraph(FarmState)

    g.add_node("predict",  node_predict)
    g.add_node("retrieve", node_retrieve)
    g.add_node("reason",   node_reason)
    g.add_node("report",   node_report)

    g.add_edge(START,      "predict")
    g.add_edge("predict",  "retrieve")
    g.add_edge("retrieve", "reason")
    g.add_edge("reason",   "report")
    g.add_edge("report",   END)

    return g.compile()


# Build app
app = build_graph()


# Initialize once if running directly
if __name__ == "__main__":
    setup_knowledge_base()
    setup_model()


# ─────────────────────────────────────────────────────────────────────────────
# HELPER: INITIAL STATE
# ─────────────────────────────────────────────────────────────────────────────
def make_initial_state(farm_data: dict) -> FarmState:
    return {
        "farm_data":        farm_data,
        "yield_prediction": 0.0,
        "yield_category":   "",
        "retrieved_docs":   [],
        "llm_reasoning":    "",
        "advisory_report":  {},
        "error":            "",
    }

# # ─────────────────────────────────────────────────────────────────────────────
# # MAIN
# # ─────────────────────────────────────────────────────────────────────────────
# if __name__ == "__main__":
#     # ── 1. Setup ──────────────────────────────────────────────────────────────
#     setup_knowledge_base()
#     setup_model()

#     # ── 2. Collect Farm Input ─────────────────────────────────────────────────
#     print("\n" + "─" * 60)
#     print("  🌾  FARM ADVISORY SYSTEM — Enter Farm Details")
#     print("─" * 60)

#     farm_input = {
#         "Region":              input("Region (e.g. North / South / East / West): ").strip(),
#         "Soil_Type":           input("Soil Type (Sandy / Clay / Loam / Silty / Peaty): ").strip(),
#         "Crop":                input("Crop (Wheat / Rice / Cotton / Maize / Barley / Soybean): ").strip(),
#         "Rainfall_mm":         float(input("Rainfall (mm): ")),
#         "Temperature_Celsius": float(input("Temperature (°C): ")),
#         "Fertilizer_Used":     input("Fertilizer Used? (1 = Yes / 0 = No): ").strip() == "1",
#         "Irrigation_Used":     input("Irrigation Used? (1 = Yes / 0 = No): ").strip() == "1",
#         "Weather_Condition":   input("Weather Condition (Sunny / Rainy / Cloudy / Humid): ").strip(),
#         "Days_to_Harvest":     int(input("Days to Harvest: ")),
#     }

#     # ── 3. Run Agent ──────────────────────────────────────────────────────────
#     app.invoke(make_initial_state(farm_input))

def run_farm_advisory(farm_input: dict):
    result = app.invoke(make_initial_state(farm_input))
    return result["advisory_report"]

# ── Sample ──────────────────────────────────────────────────────────────────
# ── RUN AGENT (change farm_input values as needed) ──────────────────────────
# setup_knowledge_base()
# setup_model()
# def run_farm_advisory(farm_input: dict):
#     result = app.invoke(make_initial_state(farm_input))
#     return result["advisory_report"]

# farm_input = {
#     "Region":              "North",
#     "Soil_Type":           "Sandy",
#     "Crop":                "Wheat",
#     "Rainfall_mm":         450.0,
#     "Temperature_Celsius": 24.5,
#     "Fertilizer_Used":     True,
#     "Irrigation_Used":     False,
#     "Weather_Condition":   "Sunny",
#     "Days_to_Harvest":     120,
# }

# app.invoke(make_initial_state(farm_input));

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# langgraph
# groq
# chromadb
# sentence-transformers
# pandas
# numpy
# scikit-learn
# plotly

"""### Setup Instructions (if using any IDE)

1.  **Install Requirements**:
    Run `pip install -r requirements.txt` in your terminal.
2.  **Get GROQ API Key**:
    Go to [Groq Cloud](https://console.groq.com/keys/), create a free API Key.
3.  **Configure API Key**:
    In Colab, click the **Secrets** (key icon) on the left sidebar. Add a new secret named `GROQ_API_KEY` and paste your key.

"""







